DROP TABLE IF EXISTS DISTANCE;
DROP TABLE IF EXISTS PREFILTER_WATER;
DROP TABLE IF EXISTS POSTFILTER_WATER;
DROP TABLE IF EXISTS HUMIDITY;

CREATE TABLE IF NOT EXISTS DISTANCE(
	ID SERIAL PRIMARY KEY,
	Value DECIMAL NOT NULL,
	Timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PREFILTER_WATER(
	ID SERIAL PRIMARY KEY,
	R INTEGER NOT NULL DEFAULT 0,
	G INTEGER NOT NULL DEFAULT 0,
	B INTEGER NOT NULL DEFAULT 0,
	Timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS POSTFILTER_WATER(
	ID SERIAL PRIMARY KEY,
	R INTEGER NOT NULL DEFAULT 0,
	G INTEGER NOT NULL DEFAULT 0,
	B INTEGER NOT NULL DEFAULT 0,
	Timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS HUMIDITY(
	ID SERIAL PRIMARY KEY,
	Value DECIMAL NOT NULL,
	Timestamp TIMESTAMP DEFAULT NOW()
);